### ISSUE TITLE
下载文件的疑问

### ISSUE THREAD

**Issue by MrVokie** [netyouli/WHCNetWorkKit#10]
看你的断点续传的代码。有一个地方不是很清楚。

在下载过程中，当程序强制退出以后。

再次进入app，你的例子中的下载的进度是如何恢复到退出之前的？

我也尝试用通过读取序列化的对象的方法。但是读取的是上一次保存的序列化对象数据，并不是退出的那一刹那的下载数据信息。

`writeDiskCache`这个方法我全局搜过，似乎你也没有对强制退出App做过特殊的处理。

是我哪里看遗漏了，还请指点一二。

**Comment by MrVokie** [comment]
看到了。UIApplicationWillTerminateNotification。

也看到了

``` objc
if (self.didFinishedBlock) {
            self.didFinishedBlock(self, nil , nil, YES);
            self.didFinishedBlock = nil;
        }else if (self.delegate &&
                  [self.delegate respondsToSelector:@selector(WHCDownloadDidFinished:data:error:success:)]) {
            [self.delegate WHCDownloadDidFinished:self data:nil error:nil success:YES];
        }
```

可是为什么我的程序正在下载的时候，强制退出，再次打开，读取序列化的数据有问题，不是退出时的下载数据信息呢，难道是程序退出时，并没有来得及保存那个operation吗？。求解释。。。。

看你的程序似乎是没问题的。

**Comment by niexiaobo** [comment]
我离线中心下载进度都没有保存，楼上有这个问题吗？怎么设置啊

**Comment by niexiaobo** [comment]
原来demo后台下载没有保存下载进度
