### ISSUE TITLE
问题：下载图片，或者ogg视频文件时，会叠加下载

### ISSUE THREAD

**Issue by qimuya3** [netyouli/WHCNetWorkKit#12]
你好，我在使用该库时，发现先下载图片会有问题，请看如下描述：
1 下载的目标图片为“http://pic6.nipic.com/20100319/4022065_015310083855_2.jpg”，size=137284；下载回来的文件名叫3.jpg；
2 当我下载完成后，3.jpg非常正常，但是，再调用接口重复下载，那么3.jpg的size会变为137284*2，也就是叠加下载了一次。

请问，如何解决该问题？？

**Comment by netyouli** [comment]
原因是你们服务端没有断点处理，也就是不支持断点下载

**Comment by qimuya3** [comment]
明白，好的。谢谢，感觉该框架非常好用，再次感谢。
