### ISSUE TITLE
ssl 忽视证书～

### ISSUE THREAD

**Issue by xiaoer371** [netyouli/WHCNetWorkKit#3]
感谢作者分享。
我是这样做的：
在download 类加上一个属性。  实现下面两个代理：
# import "WHC_Download.h"

//其中canAuthenticateAgainstProtectionSpace如果返回No，将由系统自行处理。返回YES将会由后续的didReceiveAuthenticationChallenge处理。默认为No。
- (BOOL)connection:(NSURLConnection *)connection canAuthenticateAgainstProtectionSpace:(NSURLProtectionSpace *)protectionSpace
  {
  return [protectionSpace.authenticationMethod isEqualToString:NSURLAuthenticationMethodServerTrust];
  }

在didReceiveAuthenticationChallenge中要通过challenge的sender告知是否信任服务端的证书
- (void)connection:(NSURLConnection *)connection didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)challenge
  {
  if (self.trustedSSL) {
      [challenge.sender useCredential:[NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust] forAuthenticationChallenge:challenge];
  }else {
      [challenge.sender cancelAuthenticationChallenge:challenge];
  }
  }

**Comment by netyouli** [comment]
可以的
